### ISSUE TITLE
Doesn't work for hidden input

### ISSUE THREAD

**Issue by frostmark** [stimulus-components/stimulus-clipboard#1]
Noticed that it doesn't copy text from hidden fields. I think would be nice to add this

**Comment by guillaumebriday** [comment]
I think it's a browser limitation because hidden fields are not selectable. We should hide the input in CSS.

Feel free to reopen the issue if needed 👍

**Comment by tacman** [comment]
This works, but doesn't feel very clean.  type="hidden" does not.

 <input type="text" style="display: none" ...

**Comment by rreinhardt9** [comment]
One idea that I've been playing with and that's worked so far is to use [the "clipboard API"](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) for copying instead of `execCommand`. Using the clipboard API we can pull the value of of the source and write it directly to the clipboard:

```JS
  copy (event) {
    event.preventDefault()

    let text = this.sourceTarget.value

    navigator.clipboard.writeText(text).then(()=> {
      this.copied()
    });
  }
```

It also appears that `execCommand` [is deprecated anyway](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) so this would be a beneficial change in that way as well.

The only real downside I can see is that IE does not implement the clipboard API; so if we want that to work we would need to still have a fallback that uses `execCommand` when it's not available 🤔

**Comment by tacman** [comment]
Great idea.


Dropping support for IE seems reasonable.
